### PR TITLE
fix(#103): ensure the package is not included in itself 

### LINKED ISSUE #103: When using `./**/*` for files a 0 byte rpm file gets included in the package
Sample config:
```yaml
name: "app-name"
arch: "noarch"
platform: "linux"
version: "${APP_VERSION}"
files:
  ./**/* : "/some/location/"
```

Assuming I ran the following command: `nfpm pkg -f sample.yaml -t herpderp.rpm`

When the RPM gets installed I would have a 0 byte file by the name of `herpderp.rpm` in `/some/location/`.

I haven't tested if this happens with .deb as well as we only build .rpm packages.

### PR DESCRIPTION
**Pull request by djgilcrease**
ensure the package is not included in itself when using globs to match all files

Closes #103

### CODE REVIEW

File: rpm/rpm.go [hunk 1]
```diff
@@ -199,6 +200,10 @@ func createFilesInsideRPM(info *nfpm.Info, rpm *rpmpack.RPM) error {
 				return err
 			}
 			for src, dst := range globbed {
+				if strings.Contains(src, info.Target) {
```
Comment (caarlos0) [inline rpm/rpm.go]: maybe change to `strings.HasSuffix(src, info.Target)`? 

otherwise the target name in the middle of a path would be skipped as well...

**Comment by regner** [comment]
Thanks for doing that, much appreciated!

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
