### PR TITLE
fix(deb): content file modes to support gdebi

### LINKED ISSUE #856: `type: tree` creates issues in `deb` packages
### What happened?

Creating a `deb` package containing a directory using `type: tree` causes issues with the package on Ubuntu.

On Ubuntu 20 and 22, opening the package with `Software Install` fails with the error message `Failed to install file: not supported.

On Ubuntu 24, `App Center` opens and installs the package without issues.

On all three Ubuntu versions, `gdebi` reports `List of files for 'package.deb' could not be read` in the `Included files` tab.

### How can we reproduce this?

Create a directory containing a single file using `mkdir directory && echo content > directory/file`.
Generate a `deb` package using the following config file
```yaml
name: package
maintainer: Test
contents:
  - src: directory
    dst: /var/lib/directory
    type: tree
```
The package will have the issues described above. However, a package generated with the following will not
```yaml
name: package
maintainer: Test
contents:
  - src: directory/file
    dst: /var/lib/directory/file
```

### nfpm version

```bash
_____ ____  __  __
 _ __ |  ___|  _ \|  \/  |
| '_ \| |_  | |_) | |\/| |
| | | |  _| |  __/| |  | |
|_| |_|_|   |_|   |_|  |_|
nfpm: a simple and 0-dependencies apk, arch linux, deb, ipk, and rpm packager written in Go
https://nfpm.goreleaser.com

GitVersion:    2.40.0
GitCommit:     db338d012a43be3c7f9c5a450eca2e279c973de4
GitTreeState:  false
BuildDate:     2024-08-29T11:36:48Z
BuiltBy:       goreleaser
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:M6WaaHeTCgNopUo9e8zgeHlOiN65LZAKqogzCJXBwYQ=
Platform:      linux/amd64
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The problem seems to come from the `data.tar` archive's format. The issue affects the package regardless of compression setting and decompressing and recompressing it does not solve the issue.
However, extracting the tar archive and recreating it creates a working package.

### PR DESCRIPTION
**Pull request by erikgeiser**
This PR fixes the file/dir modes in the `.deb` data tar headers. When creating directory entries based on actual on-disk directories, their modes ended up including some flags that confused graphical package manager frontends (`Software Install` and `gdebi`). With this PR, the mode field in the tar header only contains the permissions, because other type information is already included in other header fields.

Fixes #856.

### CODE REVIEW

**Comment by erikgeiser** [comment]
I'll deal with the failing acceptance test tomorrow.

**Comment by erikgeiser** [comment]
I accidentally broke mod time handling but it is fixed now.

File: deb/deb.go [hunk 1]
```diff
@@ -394,23 +395,19 @@ func createFilesInsideDataTar(info *nfpm.Info, tw *tar.Writer) (md5buf bytes.Buf
...
-				Name:     files.AsExplicitRelativePath(file.Destination),
-				Mode:     int64(file.FileInfo.Mode),
-				Typeflag: tar.TypeDir,
-				Format:   tar.FormatGNU,
-				Uname:    file.FileInfo.Owner,
-				Gname:    file.FileInfo.Group,
-				ModTime:  modtime.Get(info.MTime),
-			})
+			header, headerErr := tarHeader(file, info.MTime) // headerErr to avoid shadowing err
+			if err != nil {
```
Comment (caarlos0) [inline deb/deb.go:399]: I think this needs to be `if headerErr != nil`?

same in 406

**Review by caarlos0 — APPROVED** [review]
aside for that one comment, lgmt

thanks for looking into this @erikgeiser 🙏

**Comment by erikgeiser** [comment]
Good find. I took the time to refactor the function to avoid shadowing altogether and use the opportunity to add better error messages unique to each case.

**Comment by caarlos0** [comment]
amazing, thank you @erikgeiser ❤️
